name       : xorg-xwayland
version    : 22.1.3
release    : 10
source     :
    - https://xorg.freedesktop.org/archive/individual/xserver/xwayland-22.1.3.tar.xz : a712eb7bce32cd934df36814b5dd046aa670899c16fe98f2afb003578f86a1c5
license    : MIT
component  : xorg.server
summary    : X server intended for Xorg only clients to run under Wayland for backwards compatability.
description: |
    X server intended for Xorg only clients to run under Wayland for backwards compatability.
patterns   : /*
builddeps  :
    - pkgconfig(dri)
    - pkgconfig(epoxy)
    - pkgconfig(fontutil)
    - pkgconfig(gdm)
    - pkgconfig(libdrm)
    - pkgconfig(libtirpc)
    - pkgconfig(libxcvt)
    - pkgconfig(inputproto)
    - pkgconfig(nettle)
    - pkgconfig(pixman-1)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-eglstream-protocols)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xfont2)
    - pkgconfig(xkbcomp)
    - pkgconfig(xkbfile)
    - pkgconfig(xshmfence)
    - pkgconfig(xtrans)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Provided by xorg-server
    rm -fr $installdir/usr/lib64/xorg/
    rm $installdir/usr/share/man/man1/Xserver.1
