name       : xorg-xwayland
version    : 21.1.1
release    : 2
source     :
    - https://xorg.freedesktop.org/archive/individual/xserver/xwayland-21.1.1.tar.xz : 31f261ce51bbee76a6ca3ec02aa367ffa2b5efa2b98412df57ccefd7a19003ce
license    : MIT
component  : xorg.server
summary    : X server intended for Xorg only clients to run under Wayland for backwards
    compatability.
description: |
    X server intended for Xorg only clients to run under Wayland for backwards compatability.
patterns   : /*
builddeps  :
    - pkgconfig(dri)
    - pkgconfig(epoxy)
    - pkgconfig(fontutil)
    - pkgconfig(gdm)
    - pkgconfig(libdrm)
    - pkgconfig(libtirpc)
    - pkgconfig(inputproto)
    - pkgconfig(nettle)
    - pkgconfig(pixman-1)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-eglstream-protocols)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xfont2)
    - pkgconfig(xkbcomp)
    - pkgconfig(xkbfile)
    - pkgconfig(xshmfence)
    - pkgconfig(xtrans)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Provided by xorg-server
    rm -fr $installdir/usr/lib64/xorg/
    rm $installdir/usr/share/man/man1/Xserver.1
