name       : xorg-xwayland
version    : 23.1.1
release    : 16
source     :
    - https://xorg.freedesktop.org/archive/individual/xserver/xwayland-23.1.1.tar.xz : fb9461f5cb9fea5e07e91882311b0c88b43e8843b017ebac05eb5af69aa34c15
license    : MIT
component  : xorg.server
summary    : X server intended for Xorg only clients to run under Wayland for backwards compatability.
description: |
    X server intended for Xorg only clients to run under Wayland for backwards compatability.
patterns   : /*
builddeps  :
    - pkgconfig(dri)
    - pkgconfig(epoxy)
    - pkgconfig(fontutil)
    - pkgconfig(gdm)
    - pkgconfig(libdrm)
    - pkgconfig(libtirpc)
    - pkgconfig(libxcvt)
    - pkgconfig(inputproto)
    - pkgconfig(nettle)
    - pkgconfig(pixman-1)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-eglstream-protocols)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xfont2)
    - pkgconfig(xkbcomp)
    - pkgconfig(xkbfile)
    - pkgconfig(xshmfence)
    - pkgconfig(xtrans)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Provided by xorg-server
    rm -fr $installdir/usr/lib64/xorg/
    rm $installdir/usr/share/man/man1/Xserver.1
